# Generated by Django 4.1.2 on 2022-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('categorty', models.CharField(max_length=200)),
                ('fuel', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
